### PR TITLE
added bin images for 2014

### PR DESCRIPTION
**Pull request by mgriessler**

### CODE REVIEW

**Comment by forrestv** [comment]
Looks good, but I think you forgot to add the actual images. (:

**Comment by forrestv** [comment]
I added you as a developer, so after this you can commit and push directly.

**Comment by forrestv** [comment]
Also, just a tip: You could have shortened your code a bit by using random.choice(...) instead of random.shuffle(...)

**Comment by mgriessler** [comment]
Yea, I realized I forgot the pictures, they'll come in a future update.

Thanks for the tip.

**Comment by forrestv** [comment]
Can you finish this tonight? Add the pictures?

**Comment by mgriessler** [comment]
I've added the pictures and started the mission but I'm getting some errors I don't completely understand when I attempt to push to github so I've refrained from doing so until Saturday.

**Pull request closed without merging**
